version: 2
updates:
  - package-ecosystem: "gradle" 
    directory: "/" 
    target-branch: master
    schedule:
      interval: "daily"
      time: "07:00"
    labels:
      - "dependencies"
    open-pull-requests-limit: 5
    reviewers:
          - "aliaandersen"
          - "bryanateoan"
          - "MiguelUrrutiaSoler"